server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/s_m?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

jwt:
  secret: privateSecretKey123456789012345678901234567890PrivateApp
  expiration: 86400000

cors:
  allowed-origins: http://localhost:3000,https://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

app:
  private-mode: true
  require-invitation: false
  admin-email: raghuram@admin.com

logging:
  level:
    com.socialmedia: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG